#!/bin/bash
set -e

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}
: ${BUILD:=$(pwd)/build}

check()
{
    local hash=$1
    local file=$2

    if [ ! -e "$file" ]; then
        return 1
    fi

    CURRENT=$(shasum -a 1 $file | awk '{print $1}')

    [ "$hash" = "$CURRENT" ]
}

download()
{
    mkdir -p ${ARTIFACTS}

    local url=$2
    local file=${ARTIFACTS}/$(basename $2)
    local hash=$1

    if ! check $hash $file; then
        curl -sL $url > $file
    fi

    if ! check $hash $file; then
        echo "ERROR: $file does not match checksum $hash, got $CURRENT" 1>&2
        return 1
    fi
}

mkdir -p ${BUILD}

if [ ! -e base-image/dist/base-files.tar.gz ]; then
    base-image/build.sh
fi

cp base-image/dist/base-files.tar.gz build/

# Download docker armhf binary
ID=$(docker run -d ubuntu sh -c "apt-get update && apt-get install -y wget && wget https://downloads.hypriot.com/docker-hypriot_1.8.2-1_armhf.deb && dpkg-deb -x docker-hypriot_1.8.2-1_armhf.deb hypriot")
docker logs -f ${ID} &
docker wait ${ID}
docker cp ${ID}:/hypriot/usr/bin/docker build/

# We got ca-certificates for free...
docker cp ${ID}:/etc/ssl/certs/ca-certificates.crt build/
docker rm -vf ${ID} || true